### ISSUE TITLE
Osx 10.12.1 Sierra

### ISSUE THREAD

**Issue by Darkmadda** [kwhat/jnativehook#128]
The compile works properly on OSX Sierra. But it crashes when i try to run it. I've been able to compile it in linux and that works, so i think the code is working, I'm guessing this has something to do with the osx binary driver. Below is the error i get 

`Tue Nov 08 18:26:36 MST 2016 WARNING:	Java_org_jnativehook_GlobalScreen_getPointerAccelerationThreshold [319]: Invalid result returned from hook_get_pointer_acceleration_threshold()!
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at org.jnativehook.example.NativeHookDemo.<init>(Unknown Source)
	at org.jnativehook.example.NativeHookDemo$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at org.jnativehook.GlobalScreen.<clinit>(Unknown Source)
	... 16 more
`

I should mention that this is when i try to run the example app. I figured i should get that working before i develop. (i do have my app using the library working on my linux box). Also in an attempt that it is an accessibility issue, i used automater to make a runnable app and added that to the accessibility settings but still no go. The app runs but then crashes (this time without any feedback)

**Comment by kwhat** [comment]
Totally normal and it is definitely a bug that should be fixed.  The underlying issue is that the native OS properties are not always available on all Operating System configurations.  Apple does not provide a pointer acceleration threshold value under normal circumstances so that property is not available.  All of these properties were formally available as java properties, and in an effort to preserve backward comparability, I added the properties back via the new method calls.  The problem is these new calls now throw exceptions in the case that the properties do not exist. Wrapping the following block with a series of try catch blocks and ignoring the exception.  I should be able to get to it this weekend if I still have a country in the morning.

**Comment by kwhat** [comment]
Please test the latest trunk.

**Comment by kwhat** [comment]
Any luck with the latest trunk?  I think it will resolve the null pointer you are experiencing.

**Comment by Raftacon** [comment]
The fix didn't seem to work for me until I wrapped the entire 2.0 compatibility section in a try-catch. (I hesitate to suggest _that_ as an official fix, however, because that in itself seems indicative of a deeper problem...?)

**Comment by FD-** [comment]
I can confirm the issue still exists in the latest snapshot (jnativehook-2.1.20161209.161645-21.jar).

**Comment by kwhat** [comment]
You are just running the demo and seeing the crash?  This is strange because I cannot reproduce on 10.10.  I will take another look.

**Comment by FD-** [comment]
Yes, I'm running the NativeHookDemo included in the jar file. The jar file I use is the newest snapshot jar from [2.1.SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/), which seems to be from December 9th, and should include the commit linked above.
I am running macOS Sierra 10.12.1 and see the exact same error trace as @Darkmadda listed above. Let me know if you need additional information!

**Comment by FD-** [comment]
Seems like the issue was a simple copy-and-paste error. I ran the changes on my computer and can confirm the issue is solved.
My guess is it worked on your computer since (as described in issue #37) the key `mouseDriverMaxSpeed` in `com.apple.universalaccess` was removed after 10.10, so `pointerAccelerationThreshold` was not null on your setup, but is null when running Sierra.

**Comment by hcrone** [comment]
I am experiencing the problem with Sierra 10.12.2 - the demo program still throws the error when it tries to register the native hook. Sorry for being dense, but I'm confused, what do I do to fix this?

**Comment by kwhat** [comment]
I need to create a new maven build for the changes to take effect.  I will post one as soon as the cross compiler is up.

**Comment by kwhat** [comment]
Is this still a problem?

**Comment by NirmanSonawane** [comment]
WARNING: Java_org_jnativehook_GlobalScreen_getPointerAccelerationThreshold [319]: Invalid result returned from hook_get_pointer_acceleration_threshold()!
org.jnativehook.NativeHookException: Failed to enable access for assistive devices.
at org.jnativehook.GlobalScreen$NativeHookThread.enable(Native Method)
at org.jnativehook.GlobalScreen$NativeHookThread.run(Unknown Source)
There was a problem registering the native hook.19:34:04.327 [Thread-10]
Failed to enable access for assistive device

I am getting these errors on Mac Mojave, I am not able to understand what the issue is?
Can anybody help!
I have also tried enabling the accessibility permissions

**Comment by kwhat** [comment]
> Failed to enable access for assistive devices. 

Just enable assistive devices under security in settings.
