### ISSUE TITLE
JnativeHook with javafx

### ISSUE THREAD

**Issue by kingtak66** [kwhat/jnativehook#53]
Hi
I am trying  to use this library in a javafx application.But It can not work with javafx controls.For example when i want to set textfield or button text in NativeMoseClicked  method NullPointerException Error occurred.It seems to be a bug in JNativeHook library.I post this problem in stackoverflow site and no solution found for it.you can see my post in Stackoverflow by bellow link:

[stackoverflow](http://stackoverflow.com/questions/30676799/nullpointerexception-error-when-trying-to-set-javafx-textfield-text-from-jnative)
 
In your opinion, this is not a bug?
I am sorry for my poor English.

**Comment by lumon13** [comment]
i don't know, i'm still trying to compile a software using this library
without a IDE, but i have difficult, well, good luck anyway

**Comment by kwhat** [comment]
I answered your stack overflow question.  Its probably not a bug, but a thread safety issues you introduced by mixing Swing components with the library dispatch thread.  Please try using `GlobalScreen.setEventDispatcher(new SwingDispatchService());` before registering the hook.

**Comment by kwhat** [comment]
Hi, Just wanted to confirm that the problem is resolved and ask what the solution was so I can update the wiki.

Thanks.

**Comment by kingtak66** [comment]
hello
Thank you for the answer to my question.
Do I need to download a new version of this library?
What is the solution for javafx?
What should I do now?

**Comment by kwhat** [comment]
Hi, I thought you fixed the problem.  It should be the same solution with JavaFX.  Please try using `GlobalScreen.setEventDispatcher(new SwingDispatchService());` before you register the hook and make sure you initialized txt_Search before registering the hook.  Let me know if the problem persists.

**Comment by kingtak66** [comment]
Hi,
Firstly i'm sorry to bother you.
I got a little confused.You said that you fixed the problem.do you apply some changes in JNativeHook library?
according to your post I add "GlobalScreen.setEventDispatcher(new SwingDispatchService());" and initialize txt_search But still the problem is not fixed.
this is my code:

 ```java   
import java.net.URL;
import java.util.ResourceBundle;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import java.util.logging.Level;
import java.util.logging.LogManager;
import java.util.logging.Logger;
import javafx.fxml.FXML;
import org.jnativehook.GlobalScreen;
import org.jnativehook.NativeHookException;
import org.jnativehook.SwingDispatchService;
import org.jnativehook.mouse.NativeMouseEvent;
import org.jnativehook.mouse.NativeMouseListener;

public class FXMLDocumentController implements Initializable, NativeMouseListener {

    @FXML
    private TextField txt_Search;

    @Override
    public void initialize(URL url, ResourceBundle rb) {

        Listener();
    }

    public void Listener() {
        // Clear previous logging configurations.
        LogManager.getLogManager().reset();
        // Get the logger for "org.jnativehook" and set the level to off.
        Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
        logger.setLevel(Level.WARNING);

        try {
            txt_Search.setText("Initializing textfiels");//this is work and no problem is in here
            GlobalScreen.setEventDispatcher(new SwingDispatchService());
            GlobalScreen.registerNativeHook();
        } catch (NativeHookException ex) {
            System.err.println("There was a problem registering the native hook.");
            System.err.println(ex.getMessage());

            System.exit(1);
        }
        // Construct the example object.
        FXMLDocumentController example = new FXMLDocumentController();
        // Add the appropriate listeners.
        GlobalScreen.addNativeMouseListener(example);
    }

    @Override
    public void nativeMouseClicked(NativeMouseEvent nme) {
        txt_Search.setText("Mouse Clicked");

    }

    @Override
    public void nativeMousePressed(NativeMouseEvent nme) {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void nativeMouseReleased(NativeMouseEvent nme) {
        //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
      }
    }
```

and this error is occure when i am trying to run my  application:

> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
>  at FXMLDocumentController.nativeMouseClicked(FXMLDocumentController.java:65)
> at org.jnativehook.GlobalScreen$EventDispatchTask.processButtonEvent(Unknown Source)
	at org.jnativehook.GlobalScreen$EventDispatchTask.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)*

**Comment by kwhat** [comment]
The code you provided for FXMLDocumentController does not have a line 65.  It also does not initialize private TextField txt_Search which is probably why you are receiving a NullPointerException on txt_Search.setText("Mouse Clicked");  Unless I am missing something, this is definitely a problem with your code and not the library.  `private TextField txt_Search = new TextField()`; instead of `private TextField txt_Search`

**Comment by kingtak66** [comment]
I'm sorry.
 according to your guidence everything worked well, but it's working only in javafx that written with Java code. because in javafx were written in Java code I can initialize txt_search and in fxml based javafx app I can't initialize the TextField in the controller class.
this is my problem and JNativeHook works very well.
Please forgive me for my mistake.

**Comment by kwhat** [comment]
no problem, let me know if there are changes I can make on this end to make working with javafx controllers.

**Comment by kingtak66** [comment]
Thank you very much
I don't think a change is needed in the library because it works well with java code.
If i was able to solve my problem in JavaFX I announce it in this here.

**Comment by sankhaKarunasekara** [comment]
HI I have the same issure as kingtak66 did. My code is running all good with the IDE. But once I trying to export it as a jar and when I try to run It programme is executing but when It call the library It will pop the the NullPointerException. What should I do? Please help me.

**Comment by kwhat** [comment]
@sankhaKarunasekara Please open a new ticket with information about your specific problem.  You can reference this ticket by ticket #.
